# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    AccountBundle\Entity\User : plaintext
    
  role_hierarchy:

        # Un admin hérite des droits d'auteur et de modérateur

        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]

        # On garde ce rôle superadmin, il nous resservira par la suite

        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]



 
  providers:
        user_db:
            entity: { class: AccountBundle\Entity\User, property: username}
        
        
  firewalls:
      
    main:
      pattern:      ^/
      anonymous:    true
      form_login:
        default_target_path: /Marquis
        login_path: /connexion
        check_path: /login_check
      logout:
        path:       /logout
        target:     /Marquis

  access_control:

      #- { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }